export type DEVICE_HUMIDITY_HEAVY_SNOW = 0
export type DEVICE_HUMIDITY_SNOW = 1
export type DEVICE_HUMIDITY_HEAVY_RAIN = 2
export type DEVICE_HUMIDITY_RAIN = 3
export type DEVICE_HUMIDITY_CLOUDY = 4
export type DEVICE_HUMIDITY_SOME_CLOUDS = 5
export type DEVICE_HUMIDITY_SUNNY = 6
export type DEVICE_HUMIDITY_UNKNOWN = 7
export type DEVICE_HUMIDITY_UNSTABLE = 8
export type DEVICE_HUMIDITY_STABLE = 9

export type DEVICE_HUMIDITY_TYPE = DEVICE_HUMIDITY_HEAVY_SNOW | DEVICE_HUMIDITY_SNOW | DEVICE_HUMIDITY_HEAVY_RAIN | DEVICE_HUMIDITY_RAIN | DEVICE_HUMIDITY_CLOUDY | DEVICE_HUMIDITY_SOME_CLOUDS | DEVICE_HUMIDITY_SUNNY | DEVICE_HUMIDITY_UNKNOWN | DEVICE_HUMIDITY_UNSTABLE | DEVICE_HUMIDITY_STABLE

export type DEVICE_HUMIDITY_GENERAL_STABLE = 0
export type DEVICE_HUMIDITY_GENERAL_SUNNY = 1
export type DEVICE_HUMIDITY_GENERAL_CLOUDY = 2
export type DEVICE_HUMIDITY_GENERAL_UNSABLE = 3
export type DEVICE_HUMIDITY_GENERAL_THUNDERSTORM = 4
export type DEVICE_HUMIDITY_GENERAL_UNKNOWN = 5
export type DEVICE_HUMIDITY_GENERAL_CLOUDY_RAIN = 6

export type DEVICE_HUMIDITY_GENERAL_TYPE = DEVICE_HUMIDITY_GENERAL_STABLE | DEVICE_HUMIDITY_GENERAL_SUNNY | DEVICE_HUMIDITY_GENERAL_CLOUDY | DEVICE_HUMIDITY_GENERAL_UNSABLE | DEVICE_HUMIDITY_GENERAL_THUNDERSTORM | DEVICE_HUMIDITY_GENERAL_UNKNOWN | DEVICE_HUMIDITY_GENERAL_CLOUDY_RAIN

export type HUMIDITY_NORMAL = 1
export type HUMIDITY_CONFORTABLE = 2
export type HUMIDITY_DRY = 3
export type HUMIDITY_WET = 4

export type HUMIDITY_TYPE = HUMIDITY_NORMAL | HUMIDITY_CONFORTABLE | HUMIDITY_DRY | HUMIDITY_WET
