export type DEVICE_HUMIDITY_GENERAL_STABLE = 0
export type DEVICE_HUMIDITY_GENERAL_SUNNY = 1
export type DEVICE_HUMIDITY_GENERAL_CLOUDY = 2
export type DEVICE_HUMIDITY_GENERAL_UNSABLE = 3
export type DEVICE_HUMIDITY_GENERAL_THUNDERSTORM = 4
export type DEVICE_HUMIDITY_GENERAL_UNKNOWN = 5
export type DEVICE_HUMIDITY_GENERAL_CLOUDY_RAIN = 6
