export type SWITCH_COMMAND_ON = 'On'
export type SWITCH_COMMAND_OFF = 'Off'
export type SWITCH_COMMAND_TOGGLE = 'Toggle'
export type SWITCH_COMMAND_STOP = 'Stop'
export type SWITCH_COMMAND_OPEN = 'Open'
export type SWITCH_COMMAND_CLOSE = 'Close'
export type SWITCH_COMMAND_SET_LEVEL = 'Set Level'
export type SWITCH_COMMAND_TYPE = SWITCH_COMMAND_ON | SWITCH_COMMAND_OFF | SWITCH_COMMAND_TOGGLE | SWITCH_COMMAND_STOP | SWITCH_COMMAND_OPEN | SWITCH_COMMAND_CLOSE | SWITCH_COMMAND_STOP | SWITCH_COMMAND_SET_LEVEL
