export type TIMERTYPE_BEFORE_SUNRISE = 0
export type TIMERTYPE_AFTER_SUNRISE = 1
export type TIMERTYPE_ON_TIME = 2
export type TIMERTYPE_BEFORE_SUNSET = 3
export type TIMERTYPE_AFTER_SUNSET = 4
export type TIMERTYPE_FIXED_DATETIME = 5
