export interface IDeviceRecord {
  AddjMulti: Number
  AddjMulti2: Number
  AddjValue: Number
  AddjValue2: Number
  BatteryLevel: Number
  Chill: Number
  CustomImage: Number
  Data: String
  Description: String
  Direction: Number
  DirectionStr: String
  DimmerType: String
  Favorite: Boolean
  Gust: String
  HardwareDisabled: Boolean
  HardwareID: Number
  HardwareName: String
  HardwareType: String
  HardwareTypeVal: Number
  HaveDimmer: Boolean
  HaveGroupCmd: Boolean
  HaveTimeout: String
  ID: String
  Image: String
  IsSubDevice: String
  LastUpdate: String
  Level: Number
  LevelInt: Number
  MaxDimLevel: Number
  Name: String
  Notifications: String
  PlanID: Number
  PlanIDs: Number[]
  Protected: String
  ShowNotifications: Boolean
  SignalLevel: String
  Status: String
  StrParam1: String
  StrParam2: String
  SubType: String
  SwitchType: String
  SwitchTypeVal: Number
  Timers: String
  Type: String
  TypeImg: String
  Unit: Number
  Used: Number
  UsedByCamera: String
  XOffset: Number
  YOffset: Number
  idx: String
  Temp: Number
}
