export enum EDZ_COMMAND_PARAM {
  ADD_CAMERA = 'addcamera',
  ADD_LOG_MESSAGE = 'addlogmessage',
  ADD_SCENE_DEVICE = 'addscenedevice',
  ADD_SCENE_TIMER = 'addscenetimer',
  ADD_SCENE_CODE = 'addscenecode',
  ADD_HARDWARE = 'addhardware',
  ADD_TIMER_PLAN = 'addtimerplan',
  ADD_TIMER = 'addtimer',
  ADD_USER_VARIABLE = 'adduservariable',
  ADD_NOTIFICATION = 'addnotification',
  ALLOW_NEW_HARDWARE = 'allownewhardware',
  APPLY_ZWAVE_NODE_CONFIG = 'applyzwavenodeconfig',

  CLEAR_LIGHT_LOG = 'clearlightlog',
  CLEAR_TIMER = 'cleartimers',
  CLEAR_NOTIFICATIONS = 'clearnotifications',

  DEVICE_LIST = 'device_list',
  DELETE_SCENE_DEVICE = 'deletescenedevice',
  DELETE_HARDWARE = 'deletehardware',
  DELETE_DATA_POINT = 'deletedatapoint',
  DELETE_DATE_RANGE = 'deletedaterange',
  DELETE_TIMER = 'deletetimer',
  DELETE_SETPOINT_TIMER = 'deletesetpointtimer',
  DELETE_SCENE_TIMER = 'deletescenetimer',
  DELETE_NOTIFICATION = 'deletenotification',
  DUPLICATE_TIMER_PLAN = 'duplicatetimerplan',
  DISABLE_TIMER = 'disabletimer',
  DISABLE_SETPOINT_TIMER = 'disablesetpointtimer',
  DISABLE_SCENE_TIMER = 'disablescenetimer',

  ENABLE_TIMER = 'enabletimer',
  ENABLE_SETPOINT_TIMER = 'enablesetpointtimer',
  ENABLE_SCENE_TIMER = 'enablescenetimer',
  EMAIL_CAMERA_SNAPSHOP = 'emailcamerasnapshot',

  GET_LOG = 'getlog',
  GET_LIGHT_SWITCHES = 'getlightswitches',
  GET_PLAN_DEVICES = 'getplandevices',
  GET_SCENE_ACTIVATIONS = 'getsceneactivations',
  GET_SCENE_DEVICES = 'getscenedevices',
  GET_SECURITY_STATUS = 'getsecstatus',
  GET_SERVER_TIME = 'getServerTime',
  GET_SUNRISE_SUNSET = 'getSunRiseSet',
  GET_TIMER_PLANS = 'gettimerplans',
  GET_USER_VARIABLES = 'getuservariables',
  GET_VERSION = 'getversion',
  GET_NOTIFICATION_TYPES = 'getnotificationtypes',

  LMS_MEDIA_COMMAND = 'lmsmediacommand',
  KODI_MEDIA_COMMAND = 'kodimediacommand',

  RENAME_DEVICE = 'renamedevice',

  SET_ACTIVE_TIMER_PLAN = 'setactivetimerplan',
  SET_COLOR_BRIGHTNESS_VALUE = 'setcolbrightnessvalue',
  SET_DEVICE_USED = 'setdevused',
  SET_KELVIN_LEVEL = 'setkelvinlevel',
  SET_SETPOINT = 'setsetpoint',
  SEND_NOTIFICATION = 'sendnotification',
  SUN_WIND_ENABLE = 'EnableSunWind',
  SUN_WIND_DISABLE = 'DisableSunWind',
  SWITCH = 'switch',
  SWITCH_SCENE = 'switchscene',
  SWITCH_LIGHT = 'switchlight',
  SWITCH_MODAL = 'switchmodal',
  SYSTEM_REBOOT = 'system_reboot',
  SYSTEM_SHUTDOWN = 'system_shutdown',

  TRIGGER_CUSTOM_EVENT = 'customevent',

  UPDATE_CAMERA = 'updatecamera',
  UPDATE_DEVICE = 'udevice',
  UPDATE_SCENE = 'updatescene',
  UPDATE_HARDWARE = 'updatehardware',
  UPDATE_USER_VARIABLE = 'updateuservariable',
  UPDATE_TIMER_PLAN = 'updatetimerplan',
  UPDATE_TIMER = 'updatetimer',
  UPDATE_NOTIFICATION = 'updatenotification',
  VACCUM_DATABASE = 'vaccumdatabase',

  ZWAVE_BATTERY_LEVELS = 'zwavegetbatterylevels',

  // Not documented but found in Domoticz Source code
  GET_DEVICE_VALUE_OPTIONS = 'getdevicevalueoptions',
  LOGOUT = 'dologout',
  GET_UPTIME = 'GetUptime',
  MAKE_FAVORITE = 'makefavorite',
  GET_DEVICES = 'devices',
  LOGIN_CHECK = 'logincheck'
}
