export interface IdzDevice {
  AddjMulti: number
  AddjMulti2: number
  AddjValue: number
  AddjValue2: number
  BatteryLevel: number
  Chill: number
  CustomImage: number
  Data: string
  Description: string
  Direction: number
  DirectionStr: string
  DimmerType: string
  Favorite: boolean
  Gust: string
  HardwareDisabled: boolean
  HardwareID: number
  HardwareName: string
  HardwareType: string
  HardwareTypeVal: number
  HaveDimmer: boolean
  HaveGroupCmd: boolean
  HaveTimeout: string
  ID: string
  Image: string
  IsSubDevice: string
  LastUpdate: string
  Level: number
  LevelInt: number
  MaxDimLevel: number
  Name: string
  Notifications: string
  PlanID: number
  PlanIDs: number[]
  Protected: string
  ShowNotifications: boolean
  SignalLevel: string
  Status: string
  StrParam1: string
  StrParam2: string
  SubType: string
  SwitchType: string
  SwitchTypeVal: number
  Timers: string
  Type: string
  TypeImg: string
  Unit: number
  Used: number
  UsedByCamera: string
  XOffset: number
  YOffset: number
  idx: number
  Temp: number
}
